-- CREATE TABLE anonymous_user(
--     id INT AUTO_INCREMENT PRIMARY KEY,
--     name VARCHAR(255) NOT NULL DEFAULT 'ANÓNIMO',
--     register_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );

CREATE TABLE game (
   id INT AUTO_INCREMENT PRIMARY KEY,
    player_id INT NOT NULL,
    dice1 INT NOT NULL,
    dice2 INT NOT NULL,
    result BOOLEAN NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE player (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    register_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

